# Generated by Django 4.1 on 2022-11-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
